// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkfqubhmbkzvqjmhjlqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZnF1YmhtYmt6dnFqbWhqbHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDcxMzYsImV4cCI6MjA2MDIyMzEzNn0.OomoypjxCVdNogew1kQARBny6ueNE8jrUiFS5oJ09tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);